name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'node'

    - name: Install dependencies and build CSS
      run: |
        npm ci
        npm run build

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21  # ou la version de votre choix

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "StrictHostKeyChecking=no" >> ~/.ssh/config

    - name: Compile for Raspberry Pi
      run: GOOS=linux GOARCH=arm GOARM=7 go build -o monsite

    - name: Deploy to Raspberry Pi
      run: |
        scp ./cmd/gsvd.dev/tmp/main pi@${{ secrets.PI_HOSTNAME }}:/home/deployer
        ssh pi@${{ secrets.PI_HOSTNAME }} 'sudo systemctl restart nginx'
